### ISSUE TITLE
godrollpvp/godrollpve swapped

### ISSUE THREAD

**Issue by darkelement1987** [dcaslin/d2-checklist#1]
Image speaks for itself :-)

![image](https://user-images.githubusercontent.com/21128187/53454347-2925f600-3a27-11e9-92a2-9acc981c1f96.png)

**Comment by darkelement1987** [comment]
![image](https://user-images.githubusercontent.com/21128187/53454410-5a062b00-3a27-11e9-8a8f-0899f727cfee.png)

For some reason 'godrollpve' shows me pvp godrolls, and 'godrollpvp' shows pve godrolls.

**Comment by darkelement1987** [comment]
@dcaslin

**Comment by dcaslin** [comment]
Looks like I swapped the tooltip labels. Fixed just now in 6.0.2
