### ISSUE TITLE
FA CSS cannot be retrieved on Chrome (403 Forbidden)

### ISSUE THREAD

**Issue by Gitkohn** [dcaslin/d2-checklist#106]
Since yesterday the FA icons are not loaded when using the chrome browser. 
Reproduced on different PC / Laptop.

Cannot reproduce in Microsoft Edge.

--
Looking at the response in Chromes net-viewer, I see, that I get redirected to a FA page stating "This Asset is Protected". [HTML export](https://jsfiddle.net/bztmvcfd/)

[Maybe this commit did something?](https://github.com/dcaslin/d2-checklist/commit/ca2bdb819b10ce39fecc1ed91234b996074c9b9c)

**Comment by dcaslin** [comment]
Thanks for the details! 

I started getting reports of problems overnight between Friday and Saturday. That commit was an attempt to fix things, it allegedly did fix some people. 

Apparently the FA Pro CDN is being sunset, so I spent a huge amount of time yesterday refactoring the app to replace about 450 FA icon tags with Angular tags that us the FA SVG rendering service. 

This tree shakes the fonts to only include what I use so it should, in theory, load faster, take the CDN out of the list of "things that can break" and maybe even look nicer if you zoom in a bunch.

Can you try things again and see if it works?

**Comment by Gitkohn** [comment]
It has fixed the problem on both machines I tried it on.

Thanks for the fast response and d2checklist in general.
