### ISSUE TITLE
Progress is not tracked properly on multi-tier Triumphs

### ISSUE THREAD

**Issue by AkodoRyu** [dcaslin/d2-checklist#121]
### Example

**Triumph:** Chained Up 
**Progress:** 96% 
**Tiers:**
637/50 Enemies defeated - 100 pts 
637/250 Enemies defeated - 100 pts 
637/500 Enemies defeated - 150 pts 
637/750 Enemies defeated - 100 pts

The actual progress should be 85%.
It seems that tracking takes every step separately, which leads us to calculation along the lines of (1+1+1+0,85)/4 = 0,96.

All multi-tier triumph steps seem to work based on overall progress, so completion of previous step does not affect the overall completion. It seems that progress for triumph should always be counted based on the last tier requirements. As is now, the more steps the triumph has, the more inaccurate the tracking can become. Eg. 5 tier triumph, with 4 tiers completed will always be at least 80% completed, even if tiers 1-4 account for only 10% of actual progress.

This issue makes Triumph > Closest basically unusable since most results are false - one has to hide dozens of triumphs, to find 10 that are actually closest to completion.

**Comment by dcaslin** [comment]
11.1.7 will have this
