### ISSUE TITLE
Fix Triumph sum checking

### ISSUE THREAD

**Issue by dcaslin** [dcaslin/d2-checklist#127]
Tiered triumphs probably broke this

https://old.reddit.com/r/DestinyTheGame/comments/cs6ij7/how_to_check_for_the_50_point_triumph_score_bug/f6y6igq/

**Comment by dcaslin** [comment]
11.2.3

**Comment by robojumper** [comment]
Related: Triumph score sum in tree view

https://github.com/dcaslin/d2-checklist/blob/2ccc3e2b4f732219f3b810cc34b8d3d39c3b062b/src/app/service/parse.service.ts#L2264-L2271

this should also be checking for intervals.
