### ISSUE TITLE
Differentiate armor with extra slots

### ISSUE THREAD

**Issue by dcaslin** [dcaslin/d2-checklist#139]
Iron Banner/Raid/etc has an entirely extra mod slot that is quite valuable, this should be reflected in the UI

**Comment by rafigalbur** [comment]
I was about to make a request for this but found this one. In my use case, I would like to keep some armor for different activities that have season specific mods. For example, I want to keep some armor with undying mod slot, and dawn mod slot (upcoming season). 

It would be super helpful if the unique mod slot could be shown for the item, and even better if there was a filter for it on the top bar.

**Comment by rafigalbur** [comment]
I just noticed this icon:
![image](https://user-images.githubusercontent.com/46434351/70480202-1f98e680-1aad-11ea-9cfd-796c5f57739d.png)

I can't believe I never noticed it before and its AWESOME! Is it possible to make a filter for it up top?

**Comment by dcaslin** [comment]
Lol. Literally added that this afternoon. So I only build "is:hasseasonmod" i can easily add out text filters per season, what do you think they should be? "is:seasonforgemod" or something like that?

**Comment by rafigalbur** [comment]
LOL! What are the odds!? Per season would be super helpful as well as keeping the "is:hasseasonmod". I guess keeping the naming scheme similar to DIM would be helpful.

![image](https://user-images.githubusercontent.com/46434351/70485415-e2d4eb80-1abc-11ea-9d88-8188d2857e41.png)

But honestly I was thinking more of the drop down menu filters on the top, that way people don't have to memorize search commands.
