### ISSUE TITLE
Triumph three scores: intervals not accounted for

### ISSUE THREAD

**Issue by robojumper** [dcaslin/d2-checklist#145]
https://github.com/dcaslin/d2-checklist/blob/711d37d82ef1dc81c9a862b8d3064b88381f613d/src/app/service/parse.service.ts#L2410-L2424

![grafik](https://user-images.githubusercontent.com/14299449/70855718-cc210100-1ecf-11ea-8934-f949d07a6844.png)

**Comment by dcaslin** [comment]
Oh crap, I never got around to handling this, thanks for the reminder

**Comment by robojumper** [comment]
Fixed as of 36fd60ec48cb43cd8ff02c888d1620867cebbbbf, thanks!
