### ISSUE TITLE
Add an additional "compare panel" for for armor that share element and season mod slot.

### ISSUE THREAD

**Issue by rafigalbur** [dcaslin/d2-checklist#146]
Similar to when you have multiple copies and you can click the panel to easily compare them, It would be neat to add another button to compare all armor that share element and (maybe optional) seasonal mod slot.

This would be absolutely killer for the way I manage my vault. I typically keep 1-3  items of each slot/element/season mod with varying stat spread, and this would make it a breeze to compare and quickly mark keep/junk.

**Comment by rafigalbur** [comment]
This is kind of what I had in mind.

![VE6BkdF6iI](https://user-images.githubusercontent.com/46434351/70960628-8d18ba00-204d-11ea-9359-84ba5c989e69.png)

**Comment by dcaslin** [comment]
So, in your example, compare by element would include all legendary Arc Titan Arms, right? And by season would be all legendary Arc Titan arms for Season of Undying?

**Comment by rafigalbur** [comment]
Exactly!

**Comment by dcaslin** [comment]
Try it now, I added an extra icon below the "Copies" button to show similar items. For armor it's by bucket and burn, for weapons it's by type and frame. Had to tweak the compare dialog a bit to make it work (like showing the names of disparate items in that case) but it wasn't too tough. 

This was a great idea! Let me know if you have any other suggestions for it, if not I'll close out this issue and announce it (trying to decide if i should bother exposing this on mobile).

**Comment by rafigalbur** [comment]
Omg already? You are fast bro. 

And yes, this is great! The only comments I can think of at the moment:

- All seasonal mods are grouped together, I personally would love another button that showed the same seasonal mods, in addition to slot and element.  But I can understand if that’s overkill. 
- I see they are sorted by power, it could be nice to sort by stats (recovery, for example) but it’s definitely not needed. 

Really awesome job, can’t wait to tag a bunch of stuff when I get home. (On mobile now but I remoted into my PC to see changes)

**Comment by rafigalbur** [comment]
Also I wasn’t even thinking about weapons but it’s also gonna be super useful to compare the same frames, good job!

**Comment by dcaslin** [comment]
- Do you think it's worth shoving the new button in on mobile somewhere?
- Would you group all the things by season (like all Titan arms for Season of Undying)? Or also by burn?
- Good call on the sorting, I'll probably break that out to a diff issue after this

**Comment by rafigalbur** [comment]
Another thing I noticed, Exotics show up when comparing legendary. Maybe also match the item quality?

- I would group them by season + burn. But again,  I realize must people wouldn’t need it to be that granular. 
- As for mobile, I would personally use it.

**Comment by dcaslin** [comment]
TODO

- Make compare dialog button into menu with 3 options.  (a) Compare identical, (b) Compare similar, (c) [Armor only] Compare seasonly

- Implement seasonal compare (I'll skip burn at first to try it out, as I'm curious about what I have across burns)

- Make menu and button available on mobile

- Match armor by tier (i.e. don't show exotics when looking at legendaries)

- Offer ability to sort by pretty much all row leads (power level, stats, energy, tags, etc)

**Comment by rafigalbur** [comment]
To clarify just in case, my main use would be to compare armor with similar burn AND seasonal mod. So for example if I compare a legendary Titan helmet that is solar and dawn mod, all legendary Titan helmets with solar and dawn mod would show up.

**Comment by dcaslin** [comment]
Phew... ok latest version is pushed with sorting and most of those other issues solved. Let me know how you feel on the seasons filtering w/ burn vs not. Easy enough to toggle, I'm going to go sort my gear tonight and get a feel for it myself.

**Comment by dcaslin** [comment]
And... the prod build doesn't work, hold please...

**Comment by dcaslin** [comment]
And... we're back. Font awesome's latest library breaks prod builds, but only after you load them, which isn't cool.

**Comment by rafigalbur** [comment]
Haven’t had a chance to play with it yet.  But from the screenshots you just tweeted it’s perfect! You are awesome!

**Comment by dcaslin** [comment]
Todo: fix default sort on the compare dialog (shows sorted by LL but isn't actually). Ideally use the sort from the main screen by default OR remember last dialog sort

**Comment by rafigalbur** [comment]
Ok I think when comparing with seasonal mods it would be more useful to only show same burn, at least for the way I manage my gear. 

So the options would be:
- Compare copies
- Compare similar (same burn)
- Compare season (same burn and season mod)

**Comment by rafigalbur** [comment]
Hell, thinking about it it would be even better if you kept the 3 you already have and add a 4th one with same burn and season mod. That would be ideal IMO. 

So basically:
- Compare copies
- Compare similar
- Compare season
- Compare similar/season

**Comment by rafigalbur** [comment]
Sweet! I see that you added it, but at the moment "season" and "season & burn" show the same items. Its not filtering for same burn, just season.

**Comment by dcaslin** [comment]
Oops... Ok try it now (also moved around some of the buttons and made "Compare" more obvious to click)

**Comment by rafigalbur** [comment]
So far everything looks perfect. Excellent job!
