### ISSUE TITLE
Hawthorne's Field-Forged Shotgun cuts into other text due to its length

### ISSUE THREAD

**Issue by ImmortalZypther** [dcaslin/d2-checklist#149]
Just as described, here's an image:

![image](https://user-images.githubusercontent.com/21045587/71496073-441bef00-281f-11ea-9ad8-a215a96a86be.png)

**Comment by dcaslin** [comment]
Ecch, thx for pointing that out

I don't have that gun to test directly, but "Through Fire and Flood" is also pretty long. Should be fixed in 11.5.7 I'm pushing now.

**Comment by ImmortalZypther** [comment]
Fixed, thanks for the fast response time!
