### ISSUE TITLE
Numbers not in a straight line when comparing stats & Perks spaced weirdly on some weapons

### ISSUE THREAD

**Issue by ImmortalZypther** [dcaslin/d2-checklist#150]
1. When comparing multiple weapons, the Inventory Size, Aim Assistance, Recoil Direction, and Zoom are all further than the other stats.
2. With weapons that have only 1 perk for each slot, such as masterwork weapons, the spacing quickly becomes much smaller than other weapons, leading to some difficulty when comparing mods in the same slot.

Both are shown in the image below:
![image](https://user-images.githubusercontent.com/21045587/71533518-299d5080-28c7-11ea-942c-b306d62bf07e.png)

**Comment by dcaslin** [comment]
Excellent points. I'd actually implemented that intentionally (right aligning the values that are part of the gun archetypes and not malleable stats based on perks) but you're right, it looks terrible. That value in the left is also the base value for the stat, but it really just gums up things. Just pushed 11.5.8 to clean all that up (all stats are now aligned, base stats are removed from the lead column, but base stats are indicated by a lighter font weight).

**Comment by ImmortalZypther** [comment]
Thanks again for the fast fix! I didn't realize that you had misaligned it on purpose, but I can see the use in knowing what stats are base stats instead of stats that can be changed.

What about the spacing on the perks? Since you fixed the other small issue, I can show what I mean in pictures.
This is how perks normally look with a weapon that has only 1 perk in sight type and 1 perk in magazine type compared to a weapon with 2 in each. 
![image](https://user-images.githubusercontent.com/21045587/71545638-b265cc00-295b-11ea-9a01-3d89ce3e5e41.png)
I'm proposing you change it to look like this to have a more consistent look in the perks along with making it easier to see at a glance what perks line up with what other perks.
![image](https://user-images.githubusercontent.com/21045587/71545726-8860d980-295c-11ea-96ea-8e2da7285f9b.png)

**Comment by dcaslin** [comment]
Try it now, 11.6.0 I made each socket a cell and have it span multiple rows, so they all align now

**Comment by ImmortalZypther** [comment]
Looks super clean now, nice job!
