### ISSUE TITLE
Tweak Bounty Tags

### ISSUE THREAD

**Issue by dcaslin** [dcaslin/d2-checklist#156]

**Comment by rafigalbur** [comment]
FYI you are probably aware but was messing around with the new shopping list (ITS AWESOME!) and saw a couple of bounties that were missing the moon tag. There may be more, haven't gone too in-depth.

![](https://i.vgy.me/YfCpzf.png)

**Comment by Rumik** [comment]
Would it be possible to create a similar tagging system for quests, and then combine them? If I have a crucibal quest, for example, I’d want to see it grouped with crucibal bounties on the home screen.

**Comment by Rumik** [comment]
I think Forge and Black Armory tags should be combined.

**Comment by Rumik** [comment]
Here’s an idea: we’re typically always working towards one quest or another, so how about an interface that allows you to choose an active quest, and the site automatically searches for bounties and other quests that synergies with it? That way you can be like “what shall I work towards today?”, pick a quest, and not have to manually search for bounties to do at the same time. Joined with the shopping list and it’s a MASSIVE time saver!

**Comment by Rumik** [comment]
And, indeed, in the Quests section of the site- the bounties tab. Any reason why each active bounty couldn’t also include the relevant tags and number of then for sale, where clicking on it would show a list that you could then add to the shopping list? :D

**Comment by dcaslin** [comment]
> Would it be possible to create a similar tagging system for quests, and then combine them? If I have a quest step involving the crucibal, for example, I’d want to see it grouped with crucibal bounties on the home screen. Or if that step of the quest involves a scout rifle, I’d want it to appear with scout rifle bounties.

That's something I may think about for the future, but quests have a much shorter useful life than bounties, so it's a significant amount of extra work for questionable gain. For quests that show up properly, the searching and "favorite" tagging on the pursuits screen can work similarly.

**Comment by dcaslin** [comment]
I'm going to remove the comments here that aren't specific to bounty tags, to keep this issue clean, feel free to make a new issue relating to quests though.
