### ISSUE TITLE
Certain Quests don’t appear in the pursuits tab

### ISSUE THREAD

**Issue by Rumik** [dcaslin/d2-checklist#157]
I’ve noticed this in the past, that certain quests don’t appear in the pursuits tab. A current example is An Impossible Task, given by Osiris. And yet one of his other quests, Time Lost And Found, does. Any ideas why?

**Comment by dcaslin** [comment]
I've seen two causes: 

1) It's not in the manifest. Some quests are "Secret" and don't show up. You can figure that out by going to data.destinysets.com and typing in the name. If it's not there, it's "secret"

2) Some quests are weird. They're not listed as normal quests in the DB, and my filters to just show quests can miss them. If this happens for several in the same way, I try to fix it, other times I just ignore it b/c it's a one off. Let me know if you see these.

**Comment by Rumik** [comment]
Hmm well the above quest is visible in the Destiny 2 app, but I’ll check Destiny Sets too.

**Comment by Rumik** [comment]
It’s there https://data.destinysets.com/i/InventoryItem:3984027906

**Comment by Rumik** [comment]
None of Saint 14’s quests are appearing either!

**Comment by dcaslin** [comment]
Hmm, do they show for you in DIM on the "progress" tab? I'm wondering if there is a 3rd world where the API doesnt' return them even though they're in the DB

**Comment by Rumik** [comment]
Yep, they’re all showing up in DIM. 
![9CAF7A95-F7E3-42A0-8A93-B9F5143BE82C](https://user-images.githubusercontent.com/1244121/71782118-83d89880-2fce-11ea-9142-28835b26bf6e.jpeg)

**Comment by dcaslin** [comment]
I think I figured this out! Will push a fix momentarily. I found that some of Saint's quests weren't showing up either and was actually able to test on my account

**Comment by dcaslin** [comment]
A long time ago I'd added a filter to only show "quests_global". The Saint quests have an empty string for type, and were thus getting filtered out. I changed it to only filter out "challenge" (since those overlap with the milestones that I report seperately) and things look good now, should be live in like 5 mins.
