### ISSUE TITLE
Unable to add friends without bungieId

### ISSUE THREAD

**Issue by ressu** [dcaslin/d2-checklist#165]
It seems that it's not possible to add a player to friends if the player doesn't have a Bungie ID. For example https://www.d2checklist.com/5/4611686018495417364 cannot be added to friends and console shows an error about bungieId not being found on null

**Comment by dcaslin** [comment]
This is excellent info thanks! TIL you can have a Destiny account without linking a Bungie.Net ID to it. I had no idea this was even possible!

**Comment by ressu** [comment]
I think if you play without cross save, it shows up like this. Well, at least it applies to stadia users...

**Comment by dcaslin** [comment]
So it looks like I don't actually need bnet id's outside of ppl that are signing in and ppl in clans (and perhaps you do need a bnet for those?). Either way, just pushed a fix for this so give it a shot. Thanks!

**Comment by ressu** [comment]
Awesome, I can confirm that the fix works. Thank you!
