### ISSUE TITLE
Suggestion for weapon comparing

### ISSUE THREAD

**Issue by kpras** [dcaslin/d2-checklist#166]
When comparing weapons and having the numeric grid of weapon stats up, would it be possible to make the currently unequipped barrels, magazines, etc.  be clickable? Then when unequipped attributes are selected, have the comparison grid update the numbers to preview what the weapon stats would be if the attribute in that slot was equipped?

![image](https://user-images.githubusercontent.com/2761959/74872276-88f56b00-5322-11ea-94f2-ab3a000177a7.png)

**Comment by dcaslin** [comment]
This would require data that I don't reliably have and would be unmaintainable. It's a good idea, but unfortunately not feasible for me to implement at this time. Thanks!
