### ISSUE TITLE
Members w privacy setting

### ISSUE THREAD

**Issue by dustT45** [dcaslin/d2-checklist#204]
I use this app faithfully to track my clan and members progress. Recently I've had a couple of new members join that I cannot track due to "Blocked by privacy settings " .... A requirement of my clan (WOLVENS LIGHT) is joining our discord server. I award seasonal and other titles based on info from D2 checklist to our members but am at a loss as to what privacy setting I need to ask them to change so their progress can be tracked... any help or answers would be helpful.... thanks in advance

**Comment by dcaslin** [comment]
Visit, Bungie.net then click "settings", then the "Privacy" tab. Make sure "Show my Progression (what I've completed in Destiny, and my current status)" is checked". If you still have problems return to the default settings which is to check everything there except "Show my non-equipped inventory". Click save. 

Thanks!
