### ISSUE TITLE
Report Gambit Prime and Reckoning weekly milestones

### ISSUE THREAD

**Issue by dcaslin** [dcaslin/d2-checklist#21]
API doesn't report it yet, I don't think. May have to get cute to grab it.

**Comment by dcaslin** [comment]
Related to https://github.com/Bungie-net/api/issues/889

**Comment by dcaslin** [comment]
Gambit Prime I can cheat and grab activity history. Unfortunately for Reckoning a single "Activity" describes a session, sorta like Escalation Protocol. This makes it impossible to deduce in the API how many times you successfully completed a Tier in a session (could be 10, could be zero, I just know you played for 2 hours).

Gambit Prime will ship in 6.3.2. Reckoning will have to wait til Bungie API changes go in, unless there's some other clever hack I can find.

**Comment by kramrm** [comment]
This was referenced at https://github.com/Bungie-net/api/issues/883#issuecomment-471641832
