### ISSUE TITLE
Feature Request: User-compiled list of tracked items (page)

### ISSUE THREAD

**Issue by asherbig** [dcaslin/d2-checklist#223]
Hey, I'm a big fan of this site, and it seems like it has the potential to do everything I would want it to do. I was thinking of building my own site to do it, but realized that your repo is open source, and that you accept PRs. That being said, I would like to start a conversation for a new feature and potentially help out with it if you're up for it.

## Feature Request

As a user, I want to be able to curate a list of time-boxed bounties/weeklies/etc that auto-updates daily.
Example flow: 

* I go to a new page with an empty list, which will get populated by items that I choose.
* Adding items: (to add a set of items to the list, you choose a category AND a filter)
  * Categories
    * I can think of milestones, bounties, and maybe seasonal quests (but mainly milestones and bounties)
  * Filters
    * User entered filter (similar to the wildcard filter on `/pursuits/bounties`)
    * One difference is that the milestones would _also_ be filterable, either by name, type, DLC required, etc. I'm not sure how much info bungie includes on those, but that is the goal.
* Daily updating the list
  * User visits their curated list, which would pull a list of all available milestone/bounty/filter sets and display all the results in one list, per character with the usual completion tracker, etc
  * Key difference for displaying bounties would be showing whether the character already acquired the bounty, or if they need to pick it up.

Example category/filter sets:
`{ category: 'bounty', filter: { vendor: 'banshee', time: 'daily' } // only dailies from banshee`
`{ category: 'bounty', filter: { vendor: 'zavala' } // dailies and weeklies from zavala`
`{ category: 'milestone', filter: { activity: 'not dlc' AND activity: 'not raid' } // no dlc or raid milestones`
yeah, the last one is getting into query building, which would definitely need a more polished approach. Those examples are more like pseudo code for what a filtered category item would look like.

We can get into technical details some more if you like the idea. Again, I'm all for being able to help with this if it's not something you're that passionate about.

**Comment by dcaslin** [comment]
Interesting suggestion. In many ways it combines the bounty shopping cart (on the home page) concept with the tracked quests and bounties on the player page, along w/ the milestones, then maybe drop it into an interface similar to the gear manager. 

It's a good idea. I kinda want to see how the changes to pursuits in the new season shake out before I do anything major, but it might do a good job reconciling a lot of disparate screens that I have now across all those items.

**Comment by asherbig** [comment]
What changes are coming up? Or just new season usually means some changes to their API?

**Comment by dcaslin** [comment]
I may have been mistaken about changes, perhaps the pursuits are getting updated next season. I recall discussions of new alternatives to bounties that don't expire.

**Comment by asherbig** [comment]
https://github.com/dcaslin/d2-checklist/pull/268
