### ISSUE TITLE
Shard Mode unnecessarily moves ghosts and vehicles

### ISSUE THREAD

**Issue by bederman** [dcaslin/d2-checklist#290]
When invoking Shard Mode, I notice that the app will attempt to move all ghosts, ships, sparrows, and shaders for some reason into the vault, I suppose because they aren't explicitly tagged as junk? This isn't how most players would expect this mode to behave, please remove this from the default behavior. I end up getting a max vault after they're moved there, and then suddenly Shard Mode stops working because nothing can be moved through my now-full vault.

**Comment by dcaslin** [comment]
Deployed last week or so
