### ISSUE TITLE
Shard Mode gives up too quickly on moving

### ISSUE THREAD

**Issue by bederman** [dcaslin/d2-checklist#291]
I notice that Shard Mode goes through each item category one-by-one to see all that can be moved out from the player, and then all that can be moved in. However, this would work better as a loop, similar to how it appears DIM behaves: if on the first run nothing could have been moved, after you loop through the other categories more space could have been made available, so you should loop again, exiting the loop after you've performed one full loop through all categories without any items being moved. This could take longer, but it's still better than having to manually hit the button several times.

**Comment by dcaslin** [comment]
Deployed last week or so!
