### ISSUE TITLE
Mod season filter for armor

### ISSUE THREAD

**Issue by msogrin** [dcaslin/d2-checklist#302]
It would be useful to have a filter for armor which can take mods from a particular season.

This is different from armor season, because armor season and mod season don't always match, e.g. new Last Wish raid armor is marked as S11 but has S4 mod slot and takes mods from S4 and S5.

Also S11 (arrivals) mod slot can take S9 (dawn) mods, which doesn't follow the rule of +1/0/-1 seasons.

**Comment by dcaslin** [comment]
15.4.2
