### ISSUE TITLE
Please add milestone for Exo survival challenge on Europa

### ISSUE THREAD

**Issue by doktor5000** [dcaslin/d2-checklist#339]
This seems missing in the list of pinnacles, thanks in advance :+1:

**Comment by dcaslin** [comment]
I think it's out there now, I happened to literally be working on it when you opened this =)

Pls confirm that we're talking about the same thing.

**Comment by doktor5000** [comment]
I don't see it yet. It's not about the Exo Stranger Challenge, it's the Exo Simulation, which awards a +2 Pinnacle. This week it's Simulation: Agility, you can select it from Europa from the map in Bray Exo Science.

On a related note, also the +2 Pinnacle from doing 5 wrathborn hunts is also missing (you need to level up the Crow for that).

And the Pinnacle from doing a 1280 empire hunt also seems missing, for completeness sake ;)

**Comment by doktor5000** [comment]
Thanks for adding the Weekly Exo Challenge :grinning: :v:

One thing I noticed, you now have a duplicate with Empire Hunt Challenge - those appear as separate. once in the empire hunt playlist and once if you have an empire hunt bounty active, but they only give one powerful, once you complete either the other will vanish.

If you find some time, maybe you can add the pinnacle from doing a 1280 empire hunt.
