### ISSUE TITLE
Fix weapon icons

### ISSUE THREAD

**Issue by jsmith0523** [dcaslin/d2-checklist#340]
Icons for updated weapons in the gear list seem to be incorrect. See attached (same weapon). Max light level looks correct.
![d2ChecklistIcon](https://user-images.githubusercontent.com/66522092/100779463-70989d80-33d6-11eb-8501-e00821704e8c.png)
![d2InGameIcon](https://user-images.githubusercontent.com/66522092/100779464-70989d80-33d6-11eb-995d-3285a24b7592.png)

**Comment by dcaslin** [comment]
Good catch, pushing tonight!
