### ISSUE TITLE
recoil not being modified by barrel in weapon status

### ISSUE THREAD

**Issue by jsmith0523** [dcaslin/d2-checklist#353]
See the attached image for arrowhead brake not being accounted for. I double checked with chambered compensator on some of my autos, and there's a similar problem. DIM appears to work just fine so I don't think it's a Bungie issue.

It would also be REALLY nice if we could have a recoil direction icon like DIM has.

<img width="457" alt="AB" src="https://user-images.githubusercontent.com/66522092/102502710-f1999b00-404c-11eb-8de6-ca7901df83b9.PNG">

**Comment by dcaslin** [comment]
So DIM really pulls out all the stops in terms of reporting stat values on guns. To date D2Checklist simply reports the stats on the standard item instance. so the visible stats in game, like range and handling, match but the invisible stats like Aim Assist and Recoil direction just show the archetypal weapon values. DIM instead adds up all the plug stats and maps them according to a bungie mapping curve and some other things. This has pros and cons. Good discussion from DIM when they made the jump here:
https://github.com/DestinyItemManager/DIM/wiki/DIM's-New-Stat-Calculations

I'll look into doing something similar in the future, need to see how big of a lift it might be.
