### ISSUE TITLE
About  FontAwesome PRO, "OriginHeaderDoesNotMatchKey" POST Error, Internationalization

### ISSUE THREAD

**Issue by eTiTan** [dcaslin/d2-checklist#360]
I'm working on the code, trying to raise a server, i find some of challenges:
- FontAwesome PRO: i changed all PRO icons temporaly for the FREE version (i never do a pull request about it)
- OriginHeaderDoesNotMatchKey Error: on [https://github.com/Bungie-net/api/issues/774](https://github.com/Bungie-net/api/issues/774) find the solution.
- i'm Native Spanish speaker

Propostals: 
- FontAwesome PRO: Migrate to [Iconify](https://iconify.design/)  [Angular Component](https://github.com/iconify/iconify-angular), i want top help on it.
- OriginHeaderDoesNotMatchKey: Add a * on "Origin Header" on the Bungie.net App Config
![Origin Header Solution](https://user-images.githubusercontent.com/13942717/48613233-70620c80-e98b-11e8-814a-68dc3b0dc0d0.png)
- I can Help with Internationalization and Spanish Translation.

I want to discuss here for all because should be a short responses, i think that "OK", "THANKS", "NICE" maybe all the responses.

Regards.

**Comment by dcaslin** [comment]
Hi. Are you running at "https://localhost:4200" in dev mode? That's what you need to have the test D2Checklist api key match the origin header.

**Comment by eTiTan** [comment]
Yeah, i'm running "https://localhost:4200" at dev mode, i think that this is not a priority, i'm focus on replace the Font awesome pro icons, giving others chance to contribute too, and implement the internationalisation too.

**Comment by dcaslin** [comment]
I'm pretty heavily invested in FontAwesome Pro at this point. Not really looking to change it.
