### ISSUE TITLE
Cold Front God Rolls

### ISSUE THREAD

**Issue by DelboyDylan** [dcaslin/d2-checklist#362]
I may be missing something, but it seems as though the god roll recommendations for the Cold Front kinetic SMG from the dawning, don't match up with PandaPax's breakdown.

https://docs.google.com/spreadsheets/d/1UlPqO4koKRcqMxl2VO4JzdgkKyY7LW07W0k91S_Yl8U/edit#gid=222338306

**Comment by dcaslin** [comment]
I unfortunately sharded my last Cold Front just the other day so I can't easily check this, but is D2Checklist matching Panda's spreadsheet? If so it's working as intended. 

I believe Panda's spreadsheet is a living document that is updated after his breakdowns drop (usually at season start) so it could be that the spreadsheet has updates beyond the breakdown.

**Comment by DelboyDylan** [comment]
Currently it does not match. For example, Panda's spreadsheet considers "Rampage" a good perk, but D2Checklist does not. Please find attached a screenshot from D2Checklist.

![ColdFront](https://user-images.githubusercontent.com/20739704/107578725-037e6100-6bec-11eb-973c-0f992efeeb89.PNG)

**Comment by dcaslin** [comment]
Hey can you test this again? I don't have a Cold Front anymore to test with. It turns out this Cold Front was reissued with new perks (the left half of the perks are old, right half new). I had been using the first hit from Panda's sheet, and thus ignoring the second. I didn't realize this was an issue in Season of Hunt, but just fixed it for Trials guns in Season of Chosen, hoping this accidentally also fixed your Cold Front. Thanks!

**Comment by DelboyDylan** [comment]
Here we go. It's showing the old and new perk combos, but not highlighting the new recommendations.

![ColdFront2](https://user-images.githubusercontent.com/20739704/109663077-9e22ed80-7b63-11eb-820c-666ae57c985d.PNG)

**Comment by dcaslin** [comment]
Can you do me a favor and:

1. Enable debug mode (visit https://www.d2checklist.com/settings to do that)
2. Post a screenshot of your cold front's row?

It should look something like this: 
![image](https://user-images.githubusercontent.com/16437968/109906205-14137b80-7c6e-11eb-8e0f-8c494e781318.png)

Thanks!

**Comment by DelboyDylan** [comment]
No problemo.

![ColdFront3](https://user-images.githubusercontent.com/20739704/110010570-58f2ed00-7d16-11eb-9601-46d107c5c19d.PNG)

**Comment by dcaslin** [comment]
Attempted fix pushed, let me know if it works out (basically I needed to update Panda's spreadsheet to follow the Astral horizon model and flag Cold Front 2.0 as a unique version)

**Comment by DelboyDylan** [comment]
Looks like that's done the trick, thanks :)
