### ISSUE TITLE
Better God/Good Roll sorting

### ISSUE THREAD

**Issue by jondthompson** [dcaslin/d2-checklist#368]
One thing that I do (and find d2-checklist to be useful for) is manually count the "PvP and PvE" god roll percs.  Your "good roll" tool seems to not care whether an item has all black or all gold percs.  I'd look further into quantifying icon into scores based on the number of items with gold or black percs.  1 point for gold, .5 points for black, 0 points for none.  

My "Hollow Words" Fusion with the following percs (my scoring in parentheses):

Charge Time (0p,0e)
Fluted Barrel\Smallbore (.5p,1e)
Accelerated Coils\Projection Fuse (.5p,0e)
Slideways(1p,0e)
Disruption Break(.5p,.5e)

would then be scored as 2.5 for PvP, and 1.5 for PvE.  I'll either infuse or shard it.

My PvE God Roll "Deafening Whisper" has the following percs:

Reload (0p,1e)
Hard Launch\Quick Launch (1p,1e)
High-Velocity Rounds\Implosion Rounds (1p,1e)
Lead from Gold(0p,1e)
Auto-Loading Holster(1p,1e)

Which results in the maximum value that all PvE god rolls have of 5, but it also shows a not-too-shabby score of 3 for PvP as well. 3 is only possible with at least one god roll perc, so really I want 3.5 or higher weapons which have to have at least two god percs and the rest good percs, or three god percs and one good perc.

Once you get into this, it can be even better automated. If I tell you (in my prefs) that all I care about are 3.5 or higher or the best seasonal thing I have, you can auto tag things and then change the tags when better items come in. So if something comes into my postmaster that is good, you can automatically put it in my inventory. At the same time you can clear out the infusion pool to my vault and when I get too full tell me what to shard.

**Comment by dcaslin** [comment]
God roll quantification is always a fraught topic, as for 1000 people we have at least 2000 different points of view. I'll give this some thought. Thanks!

**Comment by jondthompson** [comment]
Yeah, I understand that. I guess for me it's intrinsically wanting to minimize my time dealing with inventory. I used to completely ignore the rolls, sharding anything that was lower power. Completely ignoring mods other than for champions. 

Then I found dim, and it had a thumbs up and down, so I started using that. But then I learned of D2 Checklist and started playing with it and liked the god roll feature much better, and it's much easier to organize my inventory using your tools over dim, so I use your tags and your god roll database to determine what to keep and what not. It still takes time outside the game, but it's minimal (and it annoys me that I then have to go into the game to delete/upgrade stuff, but I know that's the API's restriction, and I understand why Bungie has it restricted)

**Comment by jondthompson** [comment]
The quantifier system that I described though is independent of "what is actually a god roll". It's a baseline that allows all rolls to be compared better. If it's written properly it would also be possible to weight a certain mod higher (or lower) on a certain gun type.
