### ISSUE TITLE
Option for character order on milestones page

### ISSUE THREAD

**Issue by SolidKalium** [dcaslin/d2-checklist#383]
Hi!

**Background:**
When I'm looking at my milestone's page, I can have trouble remembering which character is which when I scroll down. I think I just prefer not changing the sort order too often and this issue happens when I'm sorted with pinnacles on top, nothing hidden, and am looking at the three milestones with bright dust.

**Possible solutions:**
1. Would you consider an option for the character columns on the milestones page to be set by the order of character creation instead of by the most recent date played? Or your favorite class order.
2. It might also work to make the header stay at the top of the page if it would scroll off the top. _(position:sticky; top:0; some other css to make the table header hide the table cells beneath it)_
3. An option to sort by bright dust would be cool, but I'd probably want bounties with bright dust too if that was available. And that might detract from the current setup.

Thanks for your consideration!

I very much understand if you have other priorities. If you like one of these solutions and would be open to a pull request, I might look into it in the next few weeks.

**Comment by SolidKalium** [comment]
I realized I can just create a tampermonkey script for the sticky header. I'm closing this because I'm happy with this solution, though it's probably not complete enough to be added to the normal css.

```
    document.styleSheets[0].insertRule("\
        .default-theme table.responsive-table th {\
          position: sticky;\
          top: -1px; /* corrects for tr border not being sticky */\
          background-color: #fff;\
          z-index: 1; /* prevents x button and reset time from scrolling on top of the header. But this causes the header to be on top of the scrollbar for narrow screens (which I don't use). */\
        }\
    ");
```

**Comment by dcaslin** [comment]
Your initial question seemed to imply that there is a milestone that rewards Bright Dust, which one is that? (I'd have guess master class but I note that, if so, the manifest doesn't accurately report it)

**Comment by SolidKalium** [comment]
The 8-bounty challenges for gambit (Shady Schemes), strikes (Vanguard Service), and crucible (Live-fire Exercises) each give 120 bright dust per character per week. At the start of Beyond Light these replaced the previous pairs of weekly bounties for each activity that gave bright dust.

I don't think master class gives bright dust. The weekly bounties for Guardian Games already give bright dust.
