### ISSUE TITLE
Feature request/feedback: ignore energy type for armor stat deals

### ISSUE THREAD

**Issue by broady** [dcaslin/d2-checklist#389]
Armor stat deals is a great feature, but having the option (or default) to compare without matching energy type would be great.

I usually don't care, and if I do, I'll be spending an upgrade module to swap the energy type.

**Comment by dcaslin** [comment]
14.2.7

**Comment by dcaslin** [comment]
Just click the little gear icon and there is a new checkbox, default unchecked, to enable this!

**Comment by dcaslin** [comment]
Well, there will be once the build finishes in 3 mins

**Comment by broady** [comment]
awesome. turned it on. love!
