### ISSUE TITLE
Please readd Presage as pinnacle milestone

### ISSUE THREAD

**Issue by doktor5000** [dcaslin/d2-checklist#392]
Since Presage was fixed to drop pinnacles again, would be nice to also show the milestone for it, thanks in advance 👍

**Comment by doktor5000** [comment]
Whoa, that was quick - seems to be fixed already, appreciated 🤩

**Comment by dcaslin** [comment]
Np. I had to hack it for the moment as the milestone is missing (issue
filed w/ bungie on that), but it works by querying your activity history.
