### ISSUE TITLE
Infuse pool for upgrade token use.

### ISSUE THREAD

**Issue by jondthompson** [dcaslin/d2-checklist#398]
If I mark something "infuse" and my "upgrade" is a equal or higher level, the assumption should be made that it is available for infusing into items that would cost an upgrade token, rather than glimmer.

I'm thinking having two upgrade modes would be how this needs to play out in the workflow...  The glimmer upgrade mode would work the same as you have now. The token upgrade mode would look at all of the items that are marked infuse (or delete really) and pair them with items that would be rare to upgrade via glimmer (exotics particularly).

An alternate way is to have a "upgrade the equipped item" mode, where D2-checklist clears the character's inventory and places one item tagged infuse in it to use as a token upgrade.

**Comment by dcaslin** [comment]
When you say "token" do you mean upgrade module?

**Comment by jondthompson** [comment]
Yes

-- 
Jon Thompson
Evolve
515 360 1351

**Comment by dcaslin** [comment]
Hmm, I'm having trouble seeing how much that would do beyond existing filters (such as "Exotic" and "Infuse"). Likewise on the upgrade, if you spend the time to say "I want to upgrade my Energy Weapon" isn't it just as quick to filter by Infuse and Energy slot?

**Comment by jondthompson** [comment]
I was thinking it could be used to expand the upgrade mode to allow for upgrades with things that I expressly have chosen the upgrade tag because I want to use that item to upgrade something other than the same item. 

-- 
Jon Thompson
Evolve
515 360 1351
