### ISSUE TITLE
Festival masks ignored by d2checklist

### ISSUE THREAD

**Issue by ressu** [dcaslin/d2-checklist#399]
[Festival masks](https://destinytracker.com/destiny-2/db/items/2213504923) aren't visible in d2checklist. The fact that festival masks isn't seen by d2checklist also causes possible tags (set in DIM) to be cleared for festival masks.

This applies to festival masks of all classes. Also I'm not seeing any errors in the javascript console for this.

**Comment by dcaslin** [comment]
Me: [Reads first sentence] Meh who cares about masks, just manage them in DIM anyway

Me: [Reads second sentence] Oh! Yeah that's a problem.

**Comment by dcaslin** [comment]
This will be fixed in next push, thx for the heads up!

**Comment by ressu** [comment]
> Me: [Reads first sentence] Meh who cares about masks, just manage them in DIM anyway
> 
> Me: [Reads second sentence] Oh! Yeah that's a problem.

Thanks! That was exactly my thinking when I first noticed the issue..
