### ISSUE TITLE
Support mulit-item reddit copy/paste at https://www.d2checklist.com/gear

### ISSUE THREAD

**Issue by dcaslin** [dcaslin/d2-checklist#4]
Currently you can copy a single item in MarkDown format, to easily paste it's perks to reddit: 

![image](https://user-images.githubusercontent.com/16437968/53698151-c75ae880-3da6-11e9-9a67-5a8dcc0e1dff.png)

Add a new button to the top of the list that will copy all items matching the current filter to the clipboard (limited to a max of X b/c we don't want to spam up someone's clipboard with 400 items, do we?)

X = 20 for now

**Comment by darkelement1987** [comment]
Sounds good except for the limit 🤣

**Comment by dcaslin** [comment]
New plan is to copy all visible items. So it will default to 20, but if you raise the limit to "unlimited" you can copy 400 if you want.

**Comment by dcaslin** [comment]
Complete with 6.1.0
