### ISSUE TITLE
True Prophecy Archetype Comparisons

### ISSUE THREAD

**Issue by DelboyDylan** [dcaslin/d2-checklist#400]
When comparing the True Prophecy hand cannon with others of its archetype or frame, it seems to be treated as its own frame and will only compare against other True Prophecies.

When searching for Aggressive Frame Legendary Hand Cannons:

![TP1](https://user-images.githubusercontent.com/20739704/125761912-0a9fce3b-a0e8-46d9-8cfe-69dda23b861a.jpg)

When comparing True Prophecy By Frame:

![TP2](https://user-images.githubusercontent.com/20739704/125761978-a073ccec-7bdc-4cba-8278-177676405a80.jpg)

When comparing Igneous Hammer By Frame:

![TP3](https://user-images.githubusercontent.com/20739704/125762039-35913d55-76d5-4683-9ee6-72b02e95a5d6.jpg)

**Comment by dcaslin** [comment]
That's a great catch. TIL there are two different aggressive frames!

![image](https://user-images.githubusercontent.com/16437968/126024146-d8e0169b-3b89-47bb-8905-8cc0ab53bf31.png)

Will see about using a text match rather than hash in that case
