### ISSUE TITLE
Precision Frame Shotguns Comparisons

### ISSUE THREAD

**Issue by DelboyDylan** [dcaslin/d2-checklist#403]
There are 2 (I think) types of precision frame shotgun that are currently being compared against each other incorrectly when comparing archetypes. One type fires a slug (e.g. Heritage), whereas the other has a pellet spread (e.g. Retold Tale). This issue was presumably caused by the fix for issue #400 

![PF1](https://user-images.githubusercontent.com/20739704/126320122-7b942d6b-cb26-41c8-bc8a-6fa94d65ecc4.jpg)
![PF2](https://user-images.githubusercontent.com/20739704/126320125-133d077b-028f-4b2d-888e-29c8ee3472d0.jpg)

**Comment by dcaslin** [comment]
TIL there are two types of Precision shotguns. Interesting. I'll rollback that other change soon, thx for the heads up!

**Comment by dcaslin** [comment]
15.1.10
