### ISSUE TITLE
Lost Sectors data showing tbd for some areas

### ISSUE THREAD

**Issue by MKKubik** [dcaslin/d2-checklist#406]
Today's legendary lost sector data is showing as tbd. 
Not sure if its a bug or an incomplete feature, but adding it as I don't see any other issues related to this yet.

![image](https://user-images.githubusercontent.com/24785571/127549803-0d56d4c8-eda8-43ef-9004-135c066cc0f2.png)

**Comment by dcaslin** [comment]
I will try to get that fixed as I also fill out this seasons rotations, good catch!

**Comment by dcaslin** [comment]
15.1.4
