### ISSUE TITLE
PerkBench improvements

### ISSUE THREAD

**Issue by jsmith0523** [dcaslin/d2-checklist#440]
- add some missing masterworks (e.g. charge time for linear fusions)
- filter item view by weapon archetype or other info
- filter item view by current weapons (hide sunset weapons)

**Comment by jsmith0523** [comment]
- a shortcut on the gear page for a specific weapon that opens up that weapon’s edit screen in a new tab in perkbench (Sometimes I find that I forgot to edit a specific item and I have to go load up perkbench and search for the item I was just looking at to fix it)

**Comment by dcaslin** [comment]
Do you know of any other missing masterworks besides Charge Time on Linears?

**Comment by dcaslin** [comment]
Looks like I also need to fix "season = -1" for new guns. After that sunset weapons would be implemented as season>9 I think

**Comment by jsmith0523** [comment]
Might want to check bows… draw time and accuracy. Only other ones I can think of that are uncommon are adept.

**Comment by dcaslin** [comment]
15.5.1 for the bugfixes, (season and masterworks). Will not implement on enhancements yet as this is a very niche feature that only a handful of ppl are using.

**Comment by jsmith0523** [comment]
brain fart, there are no adept masterworks. thanks for the fix!
