### ISSUE TITLE
Completed triumphs show up as open

### ISSUE THREAD

**Issue by florisb** [dcaslin/d2-checklist#450]
If you take a look at my profile on [https://www.d2checklist.com/2/4611686018433782259/triumphs/closest](https://www.d2checklist.com/2/4611686018433782259/triumphs/closest)
There are triumphs such as "Closing Competitor" or "Trusted Right Hand" that show up as not completed. 
But in fact they are completed, in game and other apps they show up as done.
In d2 checklist not, looks like you are looking at the progress of the steps, and the step progress is wrong in the api.

**Comment by dcaslin** [comment]
Thanks for the heads up and helpful details, made it a very quick fix! Will be in 15.9.1 later today

**Comment by florisb** [comment]
Thanks for the quick response. Looks like it is not completely fixed. "Trusted Right Hand" triumph still shows up in the closest list even though it is completed.  Probably because this ones completionValue is 2.
So progress should be set to the triumphs completionValue instead of just 1.

**Comment by dcaslin** [comment]
Good call! 15.9.4 will fix it

**Comment by dcaslin** [comment]
15.9.4
