### ISSUE TITLE
Null date on clan

### ISSUE THREAD

**Issue by dcaslin** [dcaslin/d2-checklist#465]
User  LeRiffmencer shows as last played in 1969 (presumably a null date) 

https://www.d2checklist.com/clan/4327464/settings

Only they clearly played just last week.

https://www.d2checklist.com/1/4611686018459305818/milestones

Need to research more.

**Comment by hoppefalcon** [comment]
Yet anther I have found 
https://www.d2checklist.com/1/4611686018432228132/milestones

**Comment by dcaslin** [comment]
Weird it keeps shifting, now it's 4611686018465679024

Anyway, next release will say "If last played date is less than cutoff  OR lastplayed date is prior to 2000, show them". This should fix this wacky shifting blank clan level last play date.

**Comment by dcaslin** [comment]
16.3.0 is target

**Comment by dcaslin** [comment]
16.3.0

**Comment by dcaslin** [comment]
Perhaps if someone joins a clan and hasn't played yet it returns a null last played date?

![image](https://user-images.githubusercontent.com/16437968/188706451-3c1656c4-4e61-4940-8034-5f2fdd24ea83.png)

**Comment by hoppefalcon** [comment]
I think that must be it as Dakkos just updated
![Screen Shot 2022-09-06 at 2 09 35 PM](https://user-images.githubusercontent.com/18582088/188708050-9585b81c-8cd0-4ae5-937c-099b3067d7c3.jpg)
