### ISSUE TITLE
Triumphs show as incomplete that are completed

### ISSUE THREAD

**Issue by cmille34** [dcaslin/d2-checklist#466]
Not sure if this is the right place to report this issue but I figured I'd start here.  I have a couple triumphs that have been completed for quite some time in the game but they are reflected on the website. 

https://www.d2checklist.com/1/4611686018441731081/triumphs/closest

Lost Sectors 14/16
Path To Power   1330/100000

Both of these are completed when I check them in the game.  Something I can/should do to get these to sync up correctly on the website?   Thanks for the help!

**Comment by dcaslin** [comment]
Two different issues. 

Lost Sectors looks like a Bungie API bug (effects me too). I've reported that here: https://github.com/Bungie-net/api/issues/1649  If/when Bungie fixes it D2Checklist should instantly reflect the fix. 

Path To Power was instead an issue where the real-time API was reporting an on the fly completion value and I was using the manifest value (which was 100K). Will fix that 16.4.11 coming soon!
