### ISSUE TITLE
Suggestion: Add an input delay.

### ISSUE THREAD

**Issue by kpras** [dcaslin/d2-checklist#467]
Hi. I love the app and use it every time I play and would like to make a UX suggestion. It seems like the text filter triggers a new search on every key press. This often leads to a situation where I'll have to sit and wait several seconds while the app goes unresponsive while typing out a search as it starts the search immediately after one letter. The worst is when I'll remove a search string to start a new search and have to wait for the entire contents of my vault to appear. I think just adding a simple 500ms delay without a change in the search string before the search actually runs would make the whole app feel much more snappier for the user.

**Comment by dcaslin** [comment]
There actually is a slight delay already built in, but clearly it's not working well for you. Two questions: 

1. What device are you using? (curious about the CPU horsepower, as all querying is client side in memory)

2. How many rows are you showing? (if you show 100 rows on a weaker device, it can get nasty rendering)

**Comment by kpras** [comment]
1. It's an old i5 Dell 6430 that lives on my coffee table. Absolutely nothing impressive about the specs. 
2. Looks like I had it set to 50. Lowering it definitely helped a lot.

I'm ok with the long wait when resetting everything if I'm intending to reset everything. But perhaps consider upping the delay somewhat and see how it feels to use? At a casual typing pace for me, it seems like 150 is still too fast and I'll often see the gear cog appear between every letter as I enter my query.

Maybe make it a configurable value in the settings?

**Comment by kpras** [comment]
Awesome. It feels much smoother now.
