### ISSUE TITLE
Firefox Gear Not Loading

### ISSUE THREAD

**Issue by agg23** [dcaslin/d2-checklist#47]
As of around a week ago, D2Checklist will no longer load in Firefox. On attempting to access the gear page, we get the minified error:

`ERROR Error: "[object Object]"
    E https://www.d2checklist.com/polyfills.86cae2b94ad943dfc2f5.js:1
    E https://www.d2checklist.com/polyfills.86cae2b94ad943dfc2f5.js:1
    R https://www.d2checklist.com/polyfills.86cae2b94ad943dfc2f5.js:1
    invokeTask https://www.d2checklist.com/polyfills.86cae2b94ad943dfc2f5.js:1
    onInvokeTask https://www.d2checklist.com/main.9a441e523718854f0a95.js:1
    invokeTask https://www.d2checklist.com/polyfills.86cae2b94ad943dfc2f5.js:1
    runTask https://www.d2checklist.com/polyfills.86cae2b94ad943dfc2f5.js:1
    v https://www.d2checklist.com/polyfills.86cae2b94ad943dfc2f5.js:1
    invokeTask https://www.d2checklist.com/polyfills.86cae2b94ad943dfc2f5.js:1
    y https://www.d2checklist.com/polyfills.86cae2b94ad943dfc2f5.js:1
    b https://www.d2checklist.com/polyfills.86cae2b94ad943dfc2f5.js:1`

It seems rather unlikely the a polyfill would be crashing here, but I suppose it is possible. The gear page itself does not show any content, and the page sets the route to www.d2checklist.com/home.

**Comment by dcaslin** [comment]
Problem confirmed, thanks!

**Comment by dcaslin** [comment]
Root case, RegExp lookbehinds are not supported outside of Chrome (so Firefox, Safari and Edge are all broken). Compounded by not catching the error on the TargetPerkService constructor.

`'fusion rifle': '(?<!linear )fusion rifle|light reactor|^rifle|unflinching rifle|scatter projectile',`
`'machine gun': '(?<!sub)machine gun',`

**Comment by dcaslin** [comment]
Fixed!
