### ISSUE TITLE
Feature Request - lock/unlock items in the postmaster

### ISSUE THREAD

**Issue by jchunkins** [dcaslin/d2-checklist#472]
When items are in the postmaster, it would be nice to be able to lock/unlock items without having to pull them into the characters inventory. I know that other tools like destiny item manager have this feature, so presumably there should be an API for this. 

The reason I think this is useful is when you're managing a pile of incoming items. I use the inventory filter "postmaster" to see what's new, and I don't want to accidentally delete a good item, but don't necessarily have the inventory space to pull the item to lock it. Also, as soon as I pull the item, its going to drop off my "postmaster" filter, so then I can't lock it without changing my filters. Locking an item while it is in the postmaster would solve this.

P.S. Thanks for providing this tool! Keep up the great work.

**Comment by dcaslin** [comment]
Good call, I think that was a simple UI oversight, hiding the menu option incorrectly. At the moment if you tag something in your postmaster as Keep, Upgrade or Archive, D2Checklist will lock it for you when you Sync Locks (or do something else that sync's locks as a side effect, such as Shard Mode or Cheap Upgrade mode). Will target this soon.

**Comment by jchunkins** [comment]
Thanks for responding so quickly. I am looking forward to this feature.

**Comment by dcaslin** [comment]
Will be out momentarily w/ 15.12.6 thanks!
