### ISSUE TITLE
Witch Queen cleanup

### ISSUE THREAD

**Issue by dcaslin** [dcaslin/d2-checklist#475]
- Master Empire Hunt isn’t a pinnacle anymore (haven’t checked in game to see what it is; Bungie said all Europa pinnacles are gone though)
- VoG isn’t pinnacle
- I don’t see Grasp of Avarice in the list at all (it’s still a pinnacle, I checked)

- Also might be good to include unlocked weapon patterns in the Collections section (seen in game under “Patterns and Catalysts” in Collections tab)

**Comment by AgentRev** [comment]
* WQ Weekly Mission 100k (unlocked at Fynch Rank 12) has weird name: ![image](https://user-images.githubusercontent.com/1380241/155784001-6fdc6e15-209e-4dde-be93-66e5870da1fb.png)

* Hawthorne Clan Reward now says in-game it's a T2 powerful (although it could be a bug, long ago it used to say T2 while still dropping a pinnacle nonetheless, I'm not high enough to test)

* Dawning Duty is still showing up

* DSC is now legendary-only like GoS

**Comment by dcaslin** [comment]
Thanks for the extra info. I think I got most/all of these between 16.1.0 yesterday and 16.1.1 that I just pushed now. Let me know if you see anything else!

**Comment by dcaslin** [comment]
I lied, more late breaking reports took us to 16.1.5

**Comment by AgentRev** [comment]
I erroneously said that DSC is now legendary-only, but apparently it's dropping T3 powerfuls every encounter at the moment, it could be a bug or temporary until Day 1.
