### ISSUE TITLE
Tyranny of Heaven

### ISSUE THREAD

**Issue by jsmith0523** [dcaslin/d2-checklist#495]
Tyranny of Heaven in PerkBench is missing Dragonfly from the curated roll.

**Comment by jsmith0523** [comment]
I wonder if this is related to ritual weapons not appearing in the recommendations. I was hoping we could get them in somehow but if they're not in the API, I guess we can't?

**Comment by dcaslin** [comment]
Yeah curated guns are a pain. They'd have perks that were otherwise unavailable and not reported via the typical API. I don't think curated guns happen newly anymore, so I'm not going to make any major changes to support them for now.
