### ISSUE TITLE
[Feature] Add Shaped weapon perk unlock levels on hover

### ISSUE THREAD

**Issue by ProphetManX** [dcaslin/d2-checklist#509]
When clicking the option "Show recommended rolls" button, the UI gives a great breakdown of all the different rolls available to craft/reshape the weapon.  I think it would be very helpful for myself and others, if you would show at what level I need to upgrade my weapon to, so I can reshape and choose any given perk (or even display which are already unlocked vs still locked, idk)

I had gone into Shuro Chi to level up a few weapons, and I was frustrated by the lack of anywhere I could lookup and see what level I needed to hit to get the rolls I wanted (I know lvl 16 is like the max overall for every perk, but in some cases you have a level 1 weapon and are trying to just get a specific perk unlocked for a GM or other content)

![image](https://user-images.githubusercontent.com/35438914/169933639-c791fc06-c18a-4a8b-8f9e-6472489fc470.png)

![image](https://user-images.githubusercontent.com/35438914/169933660-75cef1f8-922d-4efc-9e10-e4e9e3073a7c.png)

![image](https://user-images.githubusercontent.com/35438914/169933691-95e0e17a-5c55-4ed2-ae7a-ac239b4b623b.png)

If there were a JSON file (or something) to contain all this information that you could update the UI to display it, I would be happy to help out and populate some of the perk unlock values.

**Comment by dcaslin** [comment]
Great idea. The manifest actually has it handy. Going live now w/ 17.3.0 similar to your suggestion: 

![image](https://user-images.githubusercontent.com/16437968/172065225-331c6e1f-fa7c-40e7-878f-35c22e1e5a1f.png)
