### ISSUE TITLE
[Feature] Update the Home "Lost Sectors" information area to include which Planet/Destination it's on

### ISSUE THREAD

**Issue by ProphetManX** [dcaslin/d2-checklist#510]
Right now D2Checklist is a great resource to quickly find out what the Legend/Master Lost Sector is for the day, showing which Champions, Shields, and Burns are on the menu.  However, for those of us who don't have all the Lost Sector names and destinations memorized it's a pain to have to google the location to go find it.

![image](https://user-images.githubusercontent.com/35438914/169934176-62932fe2-4217-4591-a19f-afb0f9db5b5f.png)

**Comment by dcaslin** [comment]
17.4.4
