### ISSUE TITLE
Gear page fails to load

### ISSUE THREAD

**Issue by onefifth** [dcaslin/d2-checklist#511]
Since the new season launched I'm unable to load the gear page on D2 checklist. It remains blank and throws a `TypeError: Cannot read properties of undefined (reading 'Mobility')` error. 

After doing a little digging, it looks like the culprit is a Traveler Mask from Festival of the Lost 2018. This helmet is guardian class agnostic and as a result the `destinyClass: string` parameter passed to the `isPreferred` function as part of `processItems` is equal to "Any". This causes the stat lookup to fail as `cur.stats["Any"]` returns undefined, this `cur.stats` array only has keys for "Hunter", "Titan" and "Warlock".

https://github.com/dcaslin/d2-checklist/blob/3dd5f01de019596b808085176e412e0f8839d456/src/app/service/preferred-stat.service.ts#L102

I'm not sure what the correct way to handle this case of "Any" would be! But I'd love for it to not cause the page to error out and be unusable. I want to keep my ancient gear like a weirdo!

**Comment by dcaslin** [comment]
Lol. I just debugged this whole thing, came the same conclusion, and fixed it, before I saw the email alert for this issue. Excellent analysis, thanks!

(Fix is to simply ignore case where `stats[destinyClass]` is null, which gets hit for those stupid Halloween Masks in S17, apparently b/c something changed with them slightly in between seasons)
