### ISSUE TITLE
Witch Queen Story - 100K shows as incomplete, even when completed.

### ISSUE THREAD

**Issue by michaelawill** [dcaslin/d2-checklist#514]
I've completed this milestone on all three characters and it still shows as incomplete on all three.

https://www.d2checklist.com/3/4611686018467410123/milestones

The Weekly Mission this week is "The Communion"

**Comment by dcaslin** [comment]
Good call, I just noticed this is true on my account as well. Will try to take a look this weekend to figure out which of the three is it: 

1. A bug in D2Checklist
2. A bug/change in the Bungie API that I can workaround
3. A bug in the Bungie API that I'll have to get them to fix (and I'll fill an issue if so). 

Thanks for the heads up!

**Comment by dcaslin** [comment]
Had a bad required milestone built in, this will be fixed in 17.4.4 thanks!
