### ISSUE TITLE
Firefright has roll but not displayed

### ISSUE THREAD

**Issue by znxster** [dcaslin/d2-checklist#515]
The new Firefright weapon has a roll but the perks good/do not show correctly on the weapon view.

Perkbench shows the weapon has a roll. Modifying the roll and loading it as my own rolls, the perks show correctly.

I think that means the official godrolls JSON is the source of the issue, rather than d2checklist?

Many thanks for the awesome tool. Use it every time I play D2.

**Comment by dcaslin** [comment]
Thanks! Should be fixed now. Was a typo in my hand edited json.
