### ISSUE TITLE
Feature Request - show weapons never crafted before

### ISSUE THREAD

**Issue by jchunkins** [dcaslin/d2-checklist#520]
Not sure if this is possible but it I would love a way to see what weapons are available to craft that I have never crafted before. I am constantly hitting the max Resonant Elements and looking for a quick way to bleed off some of those, and it seems like the easiest way I could do that is create a new weapon, and it does not make sense to create a weapon I've already crafted previously.

**Comment by dcaslin** [comment]
This is a great idea! 

Good news: Top of my new feature list

Bad news: Been pretty busy outside of Destiny and D2C work lately, so might take a while anyway

**Comment by dcaslin** [comment]
I lied, it's live! (hopefully I'll put a YT video and /r/destinythegame post on this with more details) but in the meantime it's on your player pattern page

![image](https://user-images.githubusercontent.com/16437968/178117902-938fd707-dd25-44ad-bb3b-9eef9b581a3b.png)

**Comment by jchunkins** [comment]
Very well done sir. Amazing turn around on this feature. Does what I expected it to do. Thank you! Keep up the great work!
