### ISSUE TITLE
Potential Bug Report: DIM sync

### ISSUE THREAD

**Issue by jchunkins** [dcaslin/d2-checklist#523]
This could just be something wrong with my browser state, or maybe the DIM sync API was down, but I hit a problem that made it seem like tags were not syncing. I have tried to set the junk tag in DIM, and then jumped over to d2-checklist, and I hit the refresh button on the [gear page](https://www.d2checklist.com/gear/weapons) and nothing happened. The only thing I could do to make it work was refresh the whole page (i.e. using the browser refresh button).

I'd be interested to know if there is something I can check for when this happens so I can provide a better bug report.

Thanks again for the great website!

**Comment by jchunkins** [comment]
In general I see the "loading..." toast when I click the refresh button on the gear page but no other toast reports appear, even after clicking refresh multiple times. If I wait long enough DIM does seem to sync up. So maybe your API calls get 200 OK but it takes DIM awhile to process it's backlog? Total speculation on my part here. In my feeble attempt to see what's happening, I tried look through the firefox web console and do see messages like `Filtering gear...`, and other things that show up as  `<unavailable>` with references to some JavaScript that's not really readable since its obfuscated and all on a single line. Bottom line is that there's no useful information that I could see.

I guess if there's nothing else I can look at or things I could do to provide more information to you, I assume there's nothing for you to follow up on. Feel free to close this if you don't think it warrants further investigation.

**Comment by dcaslin** [comment]
Most importantly, are you still seeing that right now? Or are things working ok for you? (Should be the latter; if not we've at least got a localized problem on your account)

**Comment by jchunkins** [comment]
Yes, I saw this last night around the time when I posted that comment.

**Comment by jchunkins** [comment]
My workaround continues to work where I start with tagging in DIM, and if the refresh button on the page in D2Checklist does not work, the browser refresh button will update the tags. Seems like maybe something is wrong with the refresh logic in the weapons page given that scenario. 🤷
