### ISSUE TITLE
If the cursor is over a tooltip, scrolling doesn't work

### ISSUE THREAD

**Issue by SolidKalium** [dcaslin/d2-checklist#538]
https://user-images.githubusercontent.com/5685375/212724499-3d79fac8-58f4-4980-8b2d-9f5c289ed781.mov

You can see that scrolling works when the cursor isn't over the tooltip, but if the cursor is placed on top of the tooltip, the page can't be scrolled. In the clip, you see the rubberbanding that happens when you try to scroll past the end of a page.

Browser: Chrome
Page: [Milestones](https://www.d2checklist.com/5/4611686018500895898/milestones)

**Comment by dcaslin** [comment]
How are you attempting to scroll using a mouse scroll wheel?

**Comment by SolidKalium** [comment]
I'm using a two finger touch gesture to scroll

**Comment by dcaslin** [comment]
What OS? I'm using Mac and I haven't been able to repro

**Comment by SolidKalium** [comment]
Ventura 13.1 running on an M1 chip
I'm using the trackpad built in to the computer
The clip above was in Chrome 108.0.5359.124

Here it is with Safari 16.2 as well:

https://user-images.githubusercontent.com/5685375/212924725-2a667ad2-0bb2-4a57-81b8-1f9e33e2e7db.mov

I was also able to reproduce the issue in Firefox 109.0. Firefox doesn't have an overscroll effect, so there's no visible bounce from trying to scroll where it isn't possible like with the other two browsers.

**Comment by dcaslin** [comment]
Good news: I repro'd this. Thanks for the detailed info!

Bad news: It looks like this is an artifact of my upgrading from Angular Material 12 to 14. I just spent an hour messing around w/ Scroll Strategies and haven't had any luck changing it. You can see it here https://v14.material.angular.io/components/tooltip/overview if you toggled between 12 and 14 in the upper right corner.

**Comment by dcaslin** [comment]
Ah this might help... https://github.com/angular/components/issues/25566

**Comment by dcaslin** [comment]
No dice with any of those tries. Guess we'll wait and see...

**Comment by dcaslin** [comment]
Woot! I think I got it, it'll be out in 10 mins. Once you pointed it out it was driving me crazy lol

TL:DR In Angular Material 14 there was an accessibility focused change to leave tooltips open longer to allow them to have their text selected and such. This ended up eating scroll events and causing the trouble. I found a setting that reverts to previous behavior.

**Comment by SolidKalium** [comment]
Sweet! Thanks for investigating this
