### ISSUE TITLE
Transliterate Searches for Jötunn

### ISSUE THREAD

**Issue by znxster** [dcaslin/d2-checklist#540]
It might be nice to add transliteration to the search to let Jotunn find it as well.

I don't Angular well enough but a bit of hunting found: https://developers.google.com/transliterate/v1/getting_started

I think its the only weapon that would benefit from it, some maybe excessive to add for a single item.

Could Jötunn get a secondary name of Jotunn?

As it is right now, you can find it by its name Jötunn or partial match with say "tunn" or use the filters. So the search is still very useable.

Cheers

**Comment by dcaslin** [comment]
Good call. Jotunn has been around for years, and it's the only case, sometimes simpler is better =) 

<img width="961" alt="image" src="https://user-images.githubusercontent.com/16437968/213894915-a1c29984-e549-43fb-8d3d-e95effd41bde.png">

Will be in next push in a few mins.
