### ISSUE TITLE
cold front perk suggestions not showing properly

### ISSUE THREAD

**Issue by jsmith0523** [dcaslin/d2-checklist#541]
I have stats for all one some of my cold fronts, but it's not showing at all in PerkBench so it can't suggest it. Not sure if it applies to other weapons, only found it on this one.

**Comment by jsmith0523** [comment]
showing now? sorry.

**Comment by dcaslin** [comment]
Np! You probably had an old manifest running that auto-refreshed to show the new S19 god rolls.
