### ISSUE TITLE
Add filter for "No godroll info yet" into the Godroll popup.

### ISSUE THREAD

**Issue by jondthompson** [dcaslin/d2-checklist#552]
I mark all of these "Keep" (It's the only reason I use "keep", honestly), and it would be nice to be able to filter by this and then mark all of them "Keep" at once. Interestingly enough, "not good/godroll" excludes these items (and blues), so I've been able to filter by it, tag everything in that list, tag all good/godroll, tag all blues, and what I'm left with is the "no godroll info" items, but that's rather convoluted.

**Comment by dcaslin** [comment]
Nice, yeah I mark them all as "archive" using the `is:nodata` feature. It's easy enough to put into the choicelist

20.2.4

**Comment by jondthompson** [comment]
Thanks!-- Jon ThompsonOn Mar 15, 2023, at 7:35 PM, David C Caslin ***@***.***> wrote:﻿
Closed #552 as completed.
