### ISSUE TITLE
Link to `Destiny 2 Utils` is broken

### ISSUE THREAD

**Issue by Awy64** [dcaslin/d2-checklist#553]
On the `My Info` page in the web view, the link to `Destiny 2 Utils` is broken and can not offer a secure connection anymore. My guess is that it was sold and is now being used for ads. 

I have experience in react and not angular, but I could try and see if I can fix it.

**Comment by dcaslin** [comment]
Yeah that’s my friend that quit playing  =/

I’ll update soon thx for pointing out!

**Comment by Awy64** [comment]
I wanted to check out the code. I got it running locally and just removed the link on the my info page. I'm unsure if it is anywhere else. I linked the pull request with my changes.  With it being a small change, I could also see you just including it in a upcoming change you might be doing.

No hard feelings if its not used. :D
