### ISSUE TITLE
Hung Jury SR4 not grouped

### ISSUE THREAD

**Issue by znxster** [dcaslin/d2-checklist#555]
I have three Hung Jury in my vault, each shows as a single copy.

![image](https://user-images.githubusercontent.com/1396198/227384989-84d5f4e4-aef6-483c-81b5-17f238d11a8c.png)

The top two are current season, the bottom was a previous season (so might be previous version).

**Comment by dcaslin** [comment]
Can you turn on debug mode and share a screenshot?

1. Go to https://www.d2checklist.com/settings
2. Go back to your inventory screen and share the screenshot(s) like this

![image](https://user-images.githubusercontent.com/16437968/227608248-6da068ad-e6f2-4db9-8b16-51ca3ac8a6d7.png)

I'm wondering if they have different item hashes (i.e. they're not *really* the same gun)

**Comment by dcaslin** [comment]
In my screenshot the item hash is: 681067419

**Comment by znxster** [comment]
Apologies .. thought I closed this!
