### ISSUE TITLE
Page Errors on load

### ISSUE THREAD

**Issue by znxster** [dcaslin/d2-checklist#559]
Pages are failing to load today, I would guess that it is GG that has changed something.

Home errors but the other pages just spin their loading icon.

![image](https://user-images.githubusercontent.com/1396198/235776332-f570097f-f7a7-403e-a5aa-7902ffcb024c.png)

Gear still seems to work without issue.

**Comment by jarrettone** [comment]
I am seeing the same and am trying to get a development environment up to try to contribute. Probably won't have it up fast enough, but maybe...🥉 ?

**Comment by wkearney99** [comment]
I'm seeing " Cannot read properties of undefined (reading 'resets')" errors.

**Comment by dcaslin** [comment]
v20.4.1 fixes it. 

The manifest update today had breaking changes and I didn't get a chance to notice until this evening. Thanks!
