### ISSUE TITLE
Docker-compose for d2-checklist

### ISSUE THREAD

**Issue by c0m3d1an** [dcaslin/d2-checklist#60]
Hi-
I'm currently trying to develop a docker-compose and dockerfile to merge into the tree, and am  pretty close to having it working.

Had to modify:
package.json
yarn.lock

And add files to the repo (used the ones from angular-ngrx-material-starter as a kicking-off point:
Dockerfile
docker-compose.yml
src/environments/keys.ts

Everything now installs and compiles fine, and the server APPEARS to run fine, but if I try to authorized with Battle.net (only one I've tested), the authorization state is not SAVED.

Authorization page is invoked, account information is entered, but when I return to my d2-checklist page, the "Sign In" button has not CHANGED to my Battle.net name.

Any ideas on where to go from here?  I can stick my changed files somewhere or send you some pulls if you want to try it out.

**Comment by c0m3d1an** [comment]
Ooh I figured it out - Redirect URL in the Bungie App page needs to be set to https://hostname:portnumber/auth

Let me know if you want me to issue a pull request for included change(s).

**Comment by dcaslin** [comment]
So is this an OOTB dev docker container for the site? Is it just dev or also prod?

**Comment by c0m3d1an** [comment]
It's probably more of a dev container.  I would assume a prod container would include a reverse-proxy of some sort in front of ng, or "ng build --prod".  The current config doesn't include either, but it's not too difficult to change it for prod.  (I am not remotely a node or angular expert, I work mostly in Python, but love your app and wanted to run it in a docker on my own iron).

**Comment by dcaslin** [comment]
Merged!
